# Generated by Django 4.1.5 on 2023-01-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packages',
            options={},
        ),
    ]
