# Generated by Django 4.1.5 on 2023-01-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_packages_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Clients',
            new_name='client',
        ),
        migrations.RenameModel(
            old_name='Deliverymen',
            new_name='deliveryman',
        ),
        migrations.RenameModel(
            old_name='Packages',
            new_name='package',
        ),
        migrations.DeleteModel(
            name='cities',
        ),
    ]
