# Generated by Django 4.1.5 on 2023-01-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_delete_book_delete_grocery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
