# Generated by Django 4.1.5 on 2023-01-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_rename_title_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='City',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
