# Generated by Django 4.1.5 on 2023-01-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_deliveryman_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='package_id',
            new_name='packageId',
        ),
    ]
