# Generated by Django 4.1.5 on 2023-01-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_rename_package_id_package_packageid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='packageId',
            new_name='title',
        ),
    ]
