# Generated by Django 4.1.5 on 2023-01-14 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_remove_package_assigned_to_deliveryman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.city'),
        ),
    ]
